- daaas-system/network-policies/application.yaml
> fix: deploy network policies second

- daaas-system/profiles-controller/application.yaml
@sylus  Will rolling out the AuthPolicies to Dev break anything?
> feat(authpolicies): add profiles-controller auth-policies

- daaas-system/notebook-controllers/goofys-injector/instances.jsonnet
- daaas-system/profile-controllers/kubeflow-controller/deployment.jsonnet
- daaas-system/profile-controllers/profiles-controller/application.jsonnet
Remove references to old MinIO tenants, and add any missing ones.
> fix: update references to minio instances

- daaas-system/profile-controllers/profiles-controller/application.jsonnet
Apart of https://github.com/StatCan/aaw-kubeflow-profiles-controller/issues/17 
Add requeue time env var, update target revision and image tag.
> feat: Add requeue time env

- storage-system/fdi-gateway-protected-b-system/kustomization.yaml
- storage-system/fdi-gateway-unclassified-system/kustomization.yaml
- storage-system/minio-gateway-protected-b-system/kustomization.yaml
This reverts commit 0d53a483f8189d142afa852fa353225d5795cfce.
> Revert "fix(minio): temporariliy scale down dev instances"

- daaas-system/profile-controllers/profiles-controller/application.jsonnet
- statcan-system/toleration-injector/manifest.yaml
Cherry picked 
- https://github.com/StatCan/aaw-argocd-manifests/commit/a8296903521348767e354eb898aec38a62aa9bfb
- https://github.com/StatCan/aaw-argocd-manifests/commit/d54c81c5cc2275d86eed30ae4e966d1b25526394
> feat(toleration): add new gpu node pool

- daaas-system/notebook-controllers/minio-credential-injector/instances.jsonnet
- daaas-system/profile-controllers/kubeflow-controller/deployment.jsonnet
- storage-system/kustomize-gateway/README.md
> fix(fdi-gateway): add vault configs

- monitoring-system/eck.yaml
fix(dev): update eck node.roles syntax changed for 8.0.0
> fix(dev): update eck node.roles syntax changed for 8.0.0

- daaas-system/profile-controllers/kubeflow-controller/deployment.jsonnet
- daaas-system/profile-controllers/profiles-controller/application.jsonnet
Closes https://github.com/StatCan/jupyter-apis/issues/104
> feat(i18n): i18n podDefault profile controllers

- storage-system/kustomize-gateway/base/kustomization.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/Chart.lock
- storage-system/kustomize-gateway/base/minio/charts/minio/Chart.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/README.md
- storage-system/kustomize-gateway/base/minio/charts/minio/charts/common/Chart.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/charts/common/README.md
- storage-system/kustomize-gateway/base/minio/charts/minio/charts/common/templates/_capabilities.tpl
- storage-system/kustomize-gateway/base/minio/charts/minio/charts/common/templates/_names.tpl
- storage-system/kustomize-gateway/base/minio/charts/minio/ci/values-production.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/templates/NOTES.txt
- storage-system/kustomize-gateway/base/minio/charts/minio/templates/_helpers.tpl
- storage-system/kustomize-gateway/base/minio/charts/minio/templates/api-ingress.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/templates/distributed/headless-svc.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/templates/distributed/statefulset.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/templates/gateway/deployment.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/templates/gateway/pdb.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/templates/ingress.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/templates/networkpolicy.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/templates/secrets.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/templates/service.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/templates/serviceaccount.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/templates/servicemonitor.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/templates/standalone/deployment.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/templates/tls-secrets.yaml
- storage-system/kustomize-gateway/base/minio/charts/minio/values.yaml
- storage-system/kustomize-gateway/base/minio/kustomization.yaml
- storage-system/kustomize-gateway/base/minio/values.yaml
- storage-system/kustomize-gateway/base/opa/deployment.yaml
- storage-system/kustomize-gateway/overlays/gateway-oidc/kustomization.yaml
Resolves Statcan/daaas#917
I've commented out etcd, because I want to make sure minio + opa work in dev.  Once they work I'll try to get etcd working with minio.
> feat: upgrade minio to console 

- daaas-system/notebook-scanning/notebook-scanning.yaml
Thought I did the whole
https://github.com/StatCan/aaw-argocd-manifests/blob/aaw-dev-cc-00/daaas-system/workflows-cronjob/cron.yaml#L29
but alas I still had 
https://github.com/StatCan/aaw-argocd-manifests/blob/aaw-dev-cc-00/daaas-system/notebook-scanning/notebook-scanning.yaml#L38
> fix(apiVersion): cronjob

- .gitignore
- profiles-argocd-system/template/gitea/manifest.yaml
- profiles-argocd-system/template/gitea/values.yaml
Modify `ROOT_URL` environment variable.
Relates to https://github.com/StatCan/aaw-argocd-manifests/pull/91
> @cbrown/iframe kubeflow

- daaas-system/profile-controllers/profiles-controller/application.jsonnet
https://github.com/StatCan/aaw-kubeflow-profiles-controller/pull/34 Image that was pushed as part of this PR
> chore(profiles-controller): update image tag

- profiles-argocd-system/template/gitea/manifest.yaml
- updated values.yaml file and rebuild manifest.yaml for argocd
> feat(manifest.yaml): build manifest.yaml

- profiles-argocd-system/template/gitea/Makefile
- profiles-argocd-system/template/gitea/README.md
- profiles-argocd-system/template/gitea/manifest.yaml
- profiles-argocd-system/template/gitea/values.yaml
> @cbrown/gitea manifest update

- monitoring-system/elastic/heartbeat-config.yaml
- monitoring-system/elastic/ingresses.jsonnet
- monitoring-system/elastic/manifest.yaml
Add elasticsearch, kibana and heartbeat to prod cluster.
> feat(monitoring): add elastic monitoring system

- daaas-system/profile-state-controller/deployment.yaml
- daaas-system/profile-state-controller/rbac.yaml
- profiles-argocd-system/template/gitea/manifest.yaml
CC: @saffaalvi  @blairdrummond
Add deployment for profile state controller.
> @saffa/profile state controller

- daaas-system/profile-state-controller/deployment.yaml
Update profile-state-controller image after label correction
CC: @Collinbrown95 @blairdrummond
> feat(profile-state-controller): update image with correct label

- daaas-system/profile-state-controller/deployment.yaml
CC: @blairdrummond @Collinbrown95
> feat(profile-state-controller): update image

- daaas-system/trino/application.yaml
Edit Argo application targetRevision
> chore: change targetRevision to HEAD

- monitoring-system/elastic/manifest.yaml
Include removal of destination rule that was not used or needed!
> chore(elastic): update version to latest

- monitoring-system/elastic/README.md
- monitoring-system/elastic/pipelines/fluentd-default.json
- monitoring-system/elastic/pipelines/fluentd-system.json
- monitoring-system/elastic/pipelines/fluentd-user.json
Closes https://github.com/StatCan/daaas/issues/1164
> Add Elastic documentation

- daaas-system/notebook-restarting/notebook-restarting.yaml
change to execute and fixed rbac
> fix(rbac and execute)

- daaas-system/notebook-restarting/notebook-restarting.yaml
also need patch, if i could edit this in argocd i would but i cannot
> chore(rbac): move pods to its own, add patch

- daaas-system/blob-csi-driver/application.yaml
- daaas-system/blob-csi-injector/manifest.yaml
> feat(blobcsi): add driver and injector to prod

- daaas-system/README.md
- profiles-argocd-system/template/gitea/protected-b/kustomization.yaml
- profiles-argocd-system/template/gitea/unclassified/kustomization.yaml
Add json 6902 patches for required istio annotations to allow traffic to postgres database in init container. Part of the solution to https://github.com/StatCan/daaas/issues/1191.
Add initial README.md content
> @cbrown/1191 refactor gitea
