StatCan/aaw-argocd-manifests

- storage-system/kustomize-gateway/base/minio/values.yaml
Closes StatCan/daaas#744
Uses our i18n image of minio
> feat: add i18n image for minio

- daaas-system/workflows-cronjob/cron.yaml
Update the cronjob selector which cleans up argo workflows.
Closes https://github.com/StatCan/daaas/issues/828
> update: argo workflow selector

- kubeflow/kubeflow.jsonnet
I think this is a good route for Kubeflow manifests deployment. I would recommend:
**1. Split aaw-kubeflow-manifests into a dev and prod branch**
- https://github.com/StatCan/aaw-kubeflow-manifests adopts the `aaw-dev-cc-00 (default)` and `aaw-prod-cc-00` branches
- This way, pushes to `aaw-dev-cc-00` on the aaw-kubeflow-manifests repo will be deployed immediately to dev, ditto for prod.
**2. If overlays are needed, place them in the aaw-kubeflow-manifests folders**
- If a customization is needed for a prod vs dev app (e.g. an ingress url), then in addition to the `base` folder in every aaw-kubeflow-manifests app, also include `overlays/aaw-dev-cc-00` and `overlays/aaw-prod-cc-00`
- Then the only modification that needs to be made in this repo is you modify the jsonnet file to use a …
> feat(kubeflow): add kubeflow manifests draft

- monitoring-system/eck.yaml
fix(dev): force java heap memory usage (automatic detection did not work), elastic recommendation is 50% of available memory
> fix(dev): force java heap memory usage (automatic detection did not work), elastic recommendation is 50% of available memory

- storage-system/kustomize-gateway/base/kustomization.yaml
- storage-system/kustomize-gateway/base/minio/values.yaml
- storage-system/kustomize-gateway/overlays/gateway-oidc/kustomization.yaml
Closes Statcan/daaas#917
Enabled etcd to get vault working.  
Scaled MinIO UI to one replica, to be resolved in the future.
> fix(minio): enable etcd

- kube-system/coredns-custom.yaml
The ignore path will work fine with or without an empty key being defined, and this way it does not clear the field!
> fix(argocd): remove empty key from configmap

- daaas-system/fluentd-config.yaml
- kubeflow/fluentd-config.yaml
application-controller-stateful-set-0 is flooding elasticsearch with messages that we don't need, filter them out before forwarding the rest
> chore(fluentd): add filter to kubeflow ns

- daaas-system/notebook-scanning/README.md
- daaas-system/notebook-scanning/notebook-scanning.yaml
This is an initial implementation that ideally, provides scan results. We initially do a kubectl get of notebook images to see what is present on the cluster. It then uses `crane` to initiate a pull of a docker image of our images on ACR through Artifactory. After the image has been pulled and scanned, we then query the XRAY api to get a list of violations. On that list we compare what was in there to that list of kubectl'd notebook images. If there is something shared, then we know that said image is vulnerable. 
These right now are output to the console as defined by the dockerfile in https://github.com/StatCan/aaw-contrib-containers/pull/87
~~Still need an image name once https://github.com/StatCan/aaw-contrib-containers/pull/87 gets merged and pushed.
But everything else can be …
> feat(notebook scanning): initial implementation

- daaas-system/notebook-controllers/goofys-injector/manifest.yaml
- daaas-system/notebook-controllers/minio-credential-injector/manifest.yaml
- statcan-system/toleration-injector/manifest.yaml
Cert-manager has ben updated to v1 in dev/prod clusters and v1alpha2 and v1beta1 are no longer valid, this makes argocd unhappy... also will allow the authenticated gateway to be created in prod!
> Fix(prod): certmanger version to v1

- .gitignore
- profiles-argocd-system/template/gitea/manifest.yaml
- profiles-argocd-system/template/gitea/values.yaml
Adding environment variable to specify url prefix for static hosted files.
Purpose of this feature is to enable rendering Gitea in Kubeflow iframe
> feat(gitea): add STATIC_URL_PREFIX env var

- profiles-argocd-system/template/gitea/values.yaml
- ROOT_URL should include the user's namespace to distinguish different
users' Gitea instances
> feat(values.yaml): Set Gitea ROOT_URL env variable

- daaas-system/trino/manifest.yaml
Add headless svc to avoid service proxy and allow pod to pod communication within a service with envoy configuration.
> add: trino headless svc

- daaas-system/profile-controllers/profiles-controller/application.jsonnet
Closes Statcan/daaas#1188
Configuration added corresponds to config setup in the [profiles-controller helm chart values](https://github.com/StatCan/charts/blob/master/stable/profiles-controller/values.yaml).
- add config for fdi integration
- update sha of for profiles-controller to latest build sha
> feat(blobcsi): add fdi configuration to profiles-controller

- daaas-system/profile-controllers/profiles-controller/application.jsonnet
Configuration of container templates requires an owner to clarify that these templates belong to AAW.
> fix(blobcsi): update configuration

- daaas-system/notebook-restarting/README.md
- daaas-system/notebook-restarting/notebook-restarting.yaml
Doing dry runs first, can manually edit in argocd / turn off auto-sync to fine-tune things just need it in there.
Should wait for the _other_ pr to be merged first before merging this
> feat(notebook restarts): dry-run only

- daaas-system/notebook-restarting/notebook-restarting.yaml
fixes the dry-run command and uses an updated image from one of my branches in contrib-containers
> fix(update): notebook restart image

- daaas-system/notebook-restarting/README.md
- daaas-system/notebook-restarting/notebook-restarting.yaml
this is determined by the imagedigest if the imagedigest on the pod
is different than the one retrieved from the acr.
DO NOT MERGE UNTIL THE NS AND ASSOCIATED SECRETS HAVE BEEN MADE IN THE GITLAB!
I really want this to be dry-run first. 
Uses image from https://github.com/StatCan/aaw-contrib-containers/pull/96
Closes https://github.com/StatCan/daaas/issues/1224
> feat(user restarts): restart notebooks iff new version available

- statcan-system/toleration-injector/manifest.yaml
A configmap to be used for tracking namespaces whos pods require unique tolerations to be injected. 
closes https://github.com/StatCan/daaas/issues/1197
> feat(tolerationInjector): create/mount config map to toleration injector

- statcan-system/toleration-injector/manifest.yaml
Reverts StatCan/aaw-argocd-manifests#152
- subpath reference requires correction to 'subPath'
- image reference will likely change when changes are made to toleration injector
> Revert "feat(tolerationInjector): create/mount config map to toleration injector"

- statcan-system/toleration-injector/manifest.yaml
Toleration Injector namespace configmap moved to [aaw-kubeflow-profiles](https://github.com/StatCan/aaw-kubeflow-profiles/pull/93).
> fix(tolerationInjector): update image reference and mounts
